<?php if($params['isAuthorized']): //csak akkor jelenik meg a gomb, ha be van jelentkezve ?>
    <h4 style="float: right">Bejelentkezve, mint: <?=$params['userName']?></h4>
<?php endif; ?>

<!-- Contact-->
<section class="page-section" id="contact">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Kapcsolat</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>

        <?php if ($params['info'] === "küldesSikeres") : ?>
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            <strong>Az üzenet küldése sikeresen megtörtént</strong>
        </div>
    <?php endif ?>

        <form id="contactForm" action="/Bringatura_MKK/submit-message" method="POST">
            <div class="row align-items-stretch mb-5">
                <div class="col-md-6">
                    <div class="form-group">
                        <input class="form-control" name="name" type="text" placeholder="Név" required />
                    </div>
                    <div class="form-group">
                        <input class="form-control" name="email" type="email" placeholder="Email cím" required />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group form-group-textarea mb-md-0">
                        <textarea class="form-control" name="content" placeholder="Küldj üzenetet..." required></textarea>
                    </div>
                </div>
            </div>

            <div class="text-center">
                <button class="btn btn-primary btn-xl text-uppercase" id="submitButton" type="submit">Küldés</button>
            </div>
        </form>
    </div>
</section>