<!DOCTYPE html>
<html lang="hu">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
        
    <link rel="stylesheet" href="././public/style.css">
    <title>Bringatúra_MKK_PDF</title>
</head>

<body>
    <h1>Bringatúra_MKK_PDF</h1>
    <form method="post" action="/Bringatura_MKK/genPdf">
        <button type="submit" name="gen-pdf" class="btn btn-sm btn-secondary m-2">PDF Mentése</button>
    </form>
    <form action="/Bringatura_MKK/varosok-megtekintese" method="GET">
    <button type="submit" class="btn btn-sm btn-primary m-2">Vissza a Városok listájához</button>
</form>
    <?= $params['content'] ?>
    
    

</body>

</html>