
<!DOCTYPE html>
<html lang="hu">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
        
    <link rel="stylesheet" href="././public/style.css">
    <title>Bringatúra_MKK_PDF</title>
</head>

<body>
    <!--<h1>Bringatúra_MKK_PDF</h1>                                        genPdf? 
    <?= var_dump('//////// pdf.phtml ----  '+$params["start"]);
    echo("   *****   ");
    var_dump($params["touching"]);
    echo("   *****   ");
    var_dump($params["end"]);?>
    <form method="POST" action="/Bringatura_MKK/genRoutePdf" formtarget="_blank">
        <select class="form-select" name="start"  aria-label="Disabled select example" hidden>
            <option selected value=<?= $params['start']?>><?= $params['start']?></option>
        </select>
        <select class="form-select" name="touching"  aria-label="Disabled select example" hidden>
            <option selected value=<?= $params['touching']?>><?= $params['touching']?></option>
        </select>
        <select class="form-select" name="end"  aria-label="Disabled select example" hidden>
            <option selected value=<?= $params['end']?>><?= $params['end']?></option>
        </select>
        <button type="submit" class="btn btn-sm btn-primary m-2">Generate PDF</button>
    </form>

    <form method="POST" action="/Bringatura_MKK/genRoutePdf?"> 
        <button type="submit" name="gen-pdf" class="btn btn-sm btn-warning m-2">PDF Mentése</button>
    </form>

    <form action="/Bringatura_MKK/tervezo" method="GET">
        <button type="submit" class="btn btn-sm btn-primary m-2">Vissza a Tervezőbe</button>
    </form>-->

    <?= $params['content'] ?>
</body>

</html>