
<!DOCTYPE html>
<html lang="hu">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
         
    <link rel="stylesheet" href="././public/stylePdf.css">
    <title>Bringatúra_MKK_PDF</title>
</head>

<body>
    <!--<h1>Bringatúra_MKK_PDF</h1>                                        
    <form method="POST" action="/Bringatura_MKK/genRoutePdf" formtarget="_blank">
        <select class="form-select" name="start"  aria-label="Disabled select example" hidden>
            <option selected value=<?= $params['start']?>><?= $params['start']?></option>
        </select>
        <select class="form-select" name="touching"  aria-label="Disabled select example" hidden>
            <option selected value=<?= $params['touching']?>><?= $params['touching']?></option>
        </select>
        <select class="form-select" name="end"  aria-label="Disabled select example" hidden>
            <option selected value=<?= $params['end']?>><?= $params['end']?></option>
        </select>
        <button type="submit" class="btn btn-sm btn-primary m-2">Generate PDF</button>
    </form>

    <form method="POST" action="/Bringatura_MKK/genRoutePdf?"> 
        <button type="submit" name="gen-pdf" class="btn btn-sm btn-warning m-2">PDF Mentése</button>
    </form>

    <form action="/Bringatura_MKK/tervezo" method="GET">
        <button type="submit" class="btn btn-sm btn-primary m-2">Vissza a Tervezőbe</button>
    </form>-->

    <?= $params['content'] ?>
</body>

</html>