<h1>Bringatúra_MKK_PDF</h1>                                        
    
    <form method="POST" action="/Bringatura_MKK/genRoutePdf">
        <select class="form-select" name="start" >
            <option value=<?= $params['start']?>><?= $params['start']?></option>
        </select>
        <select class="form-select" name="touching" >
            <option value=<?= $params['touching']?>><?= $params['touching']?></option>
        </select>
        <select class="form-select" name="end" >
            <option value=<?= $params['end']?>><?= $params['end']?></option>
        </select>
        <button type="submit" class="btn btn-sm btn-warning m-2">PDF Mentése</button>
    </form>
    <form action="/Bringatura_MKK/tervezo" method="GET">
        <button type="submit" class="btn btn-sm btn-primary m-2">Vissza a Tervezőbe</button>
    </form>


<table>
        <thead >
            <tr>
                <th style="display:none;">id</th>
                <th >település</th>
                <th>hely</th>
                <th> N:</th>
                <th> E:</th>
                <th>útszám</th>
                <th>táv</th>
                <th>fel</th>
                <th>le</th>
            </tr>
        </thead>
        <tbody>
            <?php 
                $ossztav = 0;
                $osszfel = 0;
                $osszle = 0;
                foreach ($params['telepulesek'] as $telepules) : 
                    $ossztav += $telepules['tav'];
                    $osszfel += $telepules['fel'];
                    $osszle += $telepules['le'];
                ?>
            <tr>
                <!--<td style="display:none;"></*?= $telepules['id']?*/></td>    -->
                <td><?= $telepules['telepules']?></td>
                <td><?= $telepules['hely']?></td>
                <td><?= $telepules['locn']?></td>
                <td><?= $telepules['loce']?></td> 
                <td><?= $telepules['utszam']?></td>   
                <td><?= $telepules['tav']?></td>
                <td><?= $telepules['fel']?></td>
                <td><?= $telepules['le']?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <h3>
        Össztáv: 
        <?= $ossztav ?>
        km
    </h3>
    <h3>
        Összes fel: 
        <?= $osszfel ?>
        méter
    </h3>
    <h3>
        Összes le: 
        <?= $osszle ?>
        méter
    </h3>
</body>