

<div class="container">
    <div >
        <hr>
        <form action="/Bringatura_MKK/utvonal" method="GET">  <!--class="row g-3" -->
            <div class="forcenter">
                <label class="form-label">Start: </label>
            </div>
            <div class="forcenter">
                <select class="form-select form-select-lg mb-3" name="start">
                    <?php foreach ($params['telepulesek'] as $telepules) : ?>
                        <option value=<?= $telepules['id']?>><?= $telepules['telepules']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="forcenter"> <!--class="col-auto"-->
                <label class="form-label">Érintésével: </label>
            </div>
            <div class="forcenter">
                <select class="form-select form-select-lg mb-3" name="touching">
                    <?php foreach ($params['telepulesek'] as $telepules) : ?>
                        <option value=<?= $telepules['id']?>><?= $telepules['telepules']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="forcenter">
                <label class="form-label">Cél: </label>
            </div>
            <div class="forcenter">
                <select class="form-select form-select-lg mb-3" name="end">
                    <?php foreach ($params['telepulesek'] as $telepules) : ?>
                        <option value=<?= $telepules['id']?>><?= $telepules['telepules']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="forcenter">
                <button type="submit" class="btn btn-success">Mutasd az utat</button>
            </div>
        </form>
        <hr>
        <form action="/Bringatura_MKK/utvonal-km" method="GET">
            <div class="forcenter">
                <label class="form-label">Start: </label>
            </div>
            <div class="forcenter">
                <select class="form-select form-select-lg mb-3" name="startId">
                    <?php foreach ($params['telepulesek'] as $telepules) : ?>
                        <option value=<?= $telepules['id']?>><?= $telepules['telepules']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="forcenter">
                <label class="form-label">Érintésével: </label>
            </div>
            <div class="forcenter">
                <select class="form-select form-select-lg mb-3" name="touchId1">
                    <?php foreach ($params['telepulesek'] as $telepules) : ?>
                        <option value=<?= $telepules['id']?>><?= $telepules['telepules']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="forcenter">
                <label class="form-label">Érintésével: </label>
            </div>
            <div class="forcenter">
                <select class="form-select form-select-lg mb-3" name="touchId2">
                    <?php foreach ($params['telepulesek'] as $telepules) : ?>
                        <option value=<?= $telepules['id']?>><?= $telepules['telepules']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="forcenter">
                <label class="form-label">Megteendő napi távolságok:</label>
            </div>
            <div class="forcenter">
                <select class="form-select form-select-lg mb-3" name="km">
                    <option value=60>60 km</option>
                    <option value=80>80 km</option>
                    <option value=100>100 km</option>
                    <option value=120>120 km</option>
                    <option value=140>140 km</option>
                    <option value=160>160 km</option>
                </select>
            </div>
            <div class="forcenter">
                <button type="submit" class="btn btn-success">Mutasd az utat</button>
            </div>
        </form>
        <hr>
    </div>
</div>
