<br>
<div ><!--  class="container"-->
    <hr>
    <h3>Indulás:&nbsp;&nbsp;&nbsp;<?= $params['telepulesek'][0]['telepules']?></h3>
    <?php 
        $hossz = count($params['telepulesek']);
    ?>
    <hr>
    <h3>Érkezés:&nbsp;&nbsp;&nbsp;<?= $params['telepulesek'][$hossz-1]['telepules']?></h3>
    <hr>
    <?php if ($params['info'] === "savedDatas") : ?>
        <div class="alert alert-success">
            Adat mentés sikeres 
        </div>
    <?php endif ?>
    <!-- Útvonal pdf-be mentése -->
    <form method="POST" action="/Bringatura_MKK/genRoutePdf" formtarget="_blank">
        <select class="form-select" name="start" hidden>
            <option selected value=<?= $params['start']?>><?= $params['start']?></option>
        </select>
        <select class="form-select" name="touching" hidden>
            <option selected value=<?= $params['touching']?>><?= $params['touching']?></option>
        </select>
        <select class="form-select" name="end" hidden>
            <option selected value=<?= $params['end']?>><?= $params['end']?></option>
        </select>
        <button type="submit" class="btn btn-sm btn-warning m-2">Útvonal mentése PDF-ként</button>
    </form>
    <!-- Útvonal adatainak adatbázisba mentése -->
    <form action="/Bringatura_MKK/utvonal-save" method="GET">
        <button type="submit" class="btn btn-sm btn-success m-2">Útvonal mentése</button>
    </form>

    <form action="/Bringatura_MKK/utvonal-valaszto" method="GET">
        <button type="submit" class="btn btn-sm btn-primary m-2">Vissza a Tervezőbe</button>
    </form>
    <br>
    
    <h3>Útvonal:</h3>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead >
                <tr>
                    <th style="display:none;">id</th>
                    <th>Település</th>
                    <th>Ellenőrzési pont</th>
                    <th>Loc. N:</th>
                    <th>Loc. E:</th>
                    <th>Útszám(ok)</th>
                    <th>Táv (km)</th>
                    <th>Fel (m)</th>
                    <th>Le (m)</th>
                </tr>
            </thead>
            <tbody>
                <?php 
                    $ossztav = 0;
                    $osszfel = 0;
                    $osszle = 0;
                    //var_dump($params['telepulesek']);
                    for ($i = 0; $i < count($params['telepulesek']); $i++) : 
                        $telepulesek = $params['telepulesek'][$i];

                        $ossztav += $telepulesek['tav'];
                        $osszfel += $telepulesek['fel'];
                        $osszle += $telepulesek['le'];
                    ?>
                    <tr>
                        <td style="display:none;"><?= $telepulesek['id']?></td>    
                        <td><?= $telepulesek['telepules']?></td>
                        <td><?= $telepulesek['hely']?></td>
                        <td><?= $telepulesek['locn']?></td>
                        <td><?= $telepulesek['loce']?></td> 
                        <td><?= $telepulesek['utszam']?></td>   
                        <td><?= $telepulesek['tav']?></td>
                        <td><?= $telepulesek['fel']?></td>
                        <td><?= $telepulesek['le']?></td>
                    </tr>
                <?php endfor; ?>
            </tbody>
        </table>
    </div>
    <h3>
        Össztáv: 
        <?= $ossztav ?>
        km
    </h3>
    <h3>
        Összes fel: 
        <?= $osszfel ?>
        méter
    </h3>
    <h3>
        Összes le: 
        <?= $osszle ?>
        méter
    </h3>
</div>