
<?php if($params['isAuthorized']): //csak akkor jelenik meg a szöveg, ha be van jelentkezve ?>
    <h3>Bejelentkezve: <?=$params['userName']?></h3>
<?php endif; ?>

<div > <!-- class="container"  -->
    <div class="container-fluid">
        <hr>
        <form action="/Bringatura_MKK/utvonal-km-saved" method="GET">
            <div class="forcenter">
                <select class="form-select" name="userid" hidden>
                    <option selected value=<?= $params['userId']?>><?= $params['userId']?></option>
                </select>
                <button type="submit" class="btn btn-warning">Mutasd a mentett utat</button>
            </div>
        </form>
        <br />
        <form action="/Bringatura_MKK/utvonal-km" method="GET">
            <div class="forcenter">
                <label class="form-label">Indulás: </label>
            </div>
            <div class="forcenter">
                <select class="form-select form-select-lg mb-3" name="startId">
                    <?php foreach ($params['telepulesek'] as $telepules) : ?>
                        <option value=<?= $telepules['id']?>><?= $telepules['telepules']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="forcenter">
                <label class="form-label">Érintsd: </label>
            </div>
            <div class="forcenter">
                <select class="form-select form-select-lg mb-3" name="touchId1">
                    <?php foreach ($params['telepulesek'] as $telepules) : ?>
                        <option value=<?= $telepules['id']?>><?= $telepules['telepules']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="forcenter">
                <label class="form-label">Érintsd: </label>
            </div>
            <div class="forcenter">
                <select class="form-select form-select-lg mb-3" name="touchId2">
                    <?php foreach ($params['telepulesek'] as $telepules) : ?>
                        <option value=<?= $telepules['id']?>><?= $telepules['telepules']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="forcenter">
                <label class="form-label">Megteendő napi távolságok:</label>
            </div>
            <div class="forcenter">
                <select class="form-select form-select-lg mb-3" name="km">
                    <option value=60>60 km</option>
                    <option value=80>80 km</option>
                    <option value=100>100 km</option>
                    <option value=120>120 km</option>
                    <option value=140>140 km</option>
                    <option value=160>160 km</option>
                </select>
            </div>
            <div class="forcenter">
                <button type="submit" class="btn btn-success">Mutasd az útvonalat</button>
            </div>
        </form>
        <hr>
    </div>
</div>
