<br>
<div class="container">
    <hr>
    <h3>Start:</h3>
    <h5><?= $params['telepulesek'][0]['telepules']?></h5>
    <?php 
        $hossz = count($params['telepulesek']);
    ?>
    <hr>
    <h3>Cél:</h3>
    <h5><?= $params['telepulesek'][$hossz-1]['telepules']?></h5>
    <hr>
    <h3>Útvonal:</h3>
    <table class="table table-striped">
        <thead >
            <tr>
                <th style="display:none;">id</th>
                <th>Település</th>
                <th>Ellenőrzési pont</th>
                <th>Loc.N:</th>
                <th>Loc.E:</th>
                <th>Útszámok</th>
                <th>Táv</th>
                <th>Fel</th>
                <th>Le</th>
            </tr>
        </thead>
        <tbody>
            <?php 
                $ossztav = 0;
                $osszfel = 0;
                $osszle = 0;
                //var_dump($params['telepulesek']);
                for ($i = 0; $i < count($params['telepulesek']); $i++) : 
                    $telepulesek = $params['telepulesek'][$i];

                    $ossztav += $telepulesek['tav'];
                    $osszfel += $telepulesek['fel'];
                    $osszle += $telepulesek['le'];
                ?>
                <tr>
                    <td style="display:none;"><?= $telepulesek['id']?></td>    
                    <td><?= $telepulesek['telepules']?></td>
                    <td><?= $telepulesek['hely']?></td>
                    <td><?= $telepulesek['locn']?></td>
                    <td><?= $telepulesek['loce']?></td> 
                    <td><?= $telepulesek['utszam']?></td>   
                    <td><?= $telepulesek['tav']?></td>
                    <td><?= $telepulesek['fel']?></td>
                    <td><?= $telepulesek['le']?></td>
                </tr>
            <?php endfor; ?>
        </tbody>
    </table>
    <h3>
        Össztáv: 
        <?= $ossztav ?>
        km
    </h3>
    <h3>
        Összes fel: 
        <?= $osszfel ?>
        méter
    </h3>
    <h3>
        Összes le: 
        <?= $osszle ?>
        méter
    </h3>
    <form method="get" action="/Bringatura_MKK/generatePdf" formtarget="_blank">
        <button type="submit" class="btn btn-sm btn-primary m-2">Generate PDF</button>
    </form>
    <form action="/Bringatura_MKK/tervezo" method="GET">
        <button type="submit" class="btn btn-sm btn-primary m-2">Vissza a Tervezőbe</button>
    </form>
    <br>
</div>