
<?php if($params['isAuthorized']): //csak akkor jelenik meg a gomb, ha be van jelentkezve ?>
    <h4 style="float: right">Bejelentkezve, mint: <?=$params['userName']?></h4>
<?php endif; ?>
<br>
<h1>MKK tervezett útvonal a teljes körre</h1>                                        
<hr>
<h3>Indulás, érkezés:&nbsp;&nbsp;&nbsp;<?= $params['telepulesek'][0]['telepules']?></h3>
<hr>
<h3>Szakasz távok:&nbsp;&nbsp;&nbsp;<?= $params['km']?> km</h3>
<hr>

<?php if ($params['info'] === "savedDatas") : ?>
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Az adatok mentése sikeresen megtörtént</strong>
    </div>
<?php endif ?>

<div class="row">
    <div class="col-md" style="text-align: center">
        <!-- Útvonal adatainak adatbázisba mentése -->
        <form action="/Bringatura_MKK/utvonal-km-save" method="GET">
                <button type="submit" class="btn btn-sm btn-success m-2">Útvonal mentése a fiókomba</button>
        </form>
    </div>
    <div class="col-md" style="text-align: center">
        <!-- Útvonal táblázatának mentése pdf-be -->
        <form method="POST" action="/Bringatura_MKK/genByKmPdf" formtarget="_blank">
            <select class="form-select" name="startId" hidden>
                <option selected value=<?= $params['startId']?>><?= $params['startId']?></option>
            </select>
            <select class="form-select" name="touchId1" hidden>
                <option selected value=<?= $params['touchId1']?>><?= $params['touchId1']?></option>
            </select>
            <select class="form-select" name="touchId2" hidden>
                <option selected value=<?= $params['touchId2']?>><?= $params['touchId2']?></option>
            </select>
            <select class="form-select" name="km" hidden>
                <option selected value=<?= $params['km']?>><?= $params['km']?></option>
            </select>
            <button type="submit" class="btn btn-sm btn-warning m-2">Útvonal mentése PDF-ként</button>
        </form>
    </div>
    <div class="col-md" style="text-align: center">
        <form action="/Bringatura_MKK/utvonal-valaszto-km" method="GET">
            <button type="submit" class="btn btn-sm btn-primary m-2">Vissza a Tervezőbe</button>
        </form>
    </div>
</div>
<br>
    
<h3>Útvonal:</h3>
<?php 
    $a = 1;
    $ossztav = 0;
    $tavszorzo = 0;
    $osszesTavolsag = 0;
    $szakaszSzama = 1;
    switch ($params['km']) {
        case 60:
            $tavszorzo = 60*93/100;
            $osszesTavolsag = 1900;
            break;
        case 80:
            $tavszorzo = 80*93/100;
            $osszesTavolsag = 1900;
            break;
        case 100:
            $tavszorzo = 100*93/100;
            $osszesTavolsag = 1900;
            break;
        case 120:
            $tavszorzo = 120*94/100;
            $osszesTavolsag = 1800;
            break;
        case 140:
            $tavszorzo = 140*95/100;
            $osszesTavolsag = 1800;
            break;
        default:
            $tavszorzo = 160*96/100;
            $osszesTavolsag = 1800;
        }
    while ($ossztav <= $osszesTavolsag) ://$a <= count($params['telepulesek'])-1) : ?>
    <h5><?= $szakaszSzama ?>. szakasz</h5>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead >
                <tr>
                    <th style="display:none;">id</th>
                    <th>Település</th>
                    <th>Ellenőrzési pont</th>
                    <th>Loc. N:</th>
                    <th>Loc. E:</th>
                    <th>Útszám(ok)</th>
                    <th>Táv (km)</th>
                    <th>Fel (m)</th>
                    <th>Le (m)</th>
                </tr>
            </thead>
            <tbody>
            <?php 
                    
                $szakaszfel = 0;
                $szakaszle = 0;
                //echo"<pre>";
                //var_dump($params['telepulesek']);
                $tav = 0;
                $first = true;
                $a -= 1; //azért kell, hogy a táblázat első sora, mindig az előző táblázat utolsó sora legyen
                //var_dump("while előtt:  ", $first);
                while ($tav <= $tavszorzo) :// 
                    
                    if ($a == 0)
                    {
                        $telepulesek = $params['telepulesek'][$a];
                        //$a += 2;
                        $first = false;
                    }
                    elseif ($first == true) // ha ez az adott táblázat első sora, kinullázza az értékeket
                    {
                        $telepulesek = $params['telepulesek'][$a];
                        $telepulesek['tav'] = 0;
                        $telepulesek['utszam'] = '----';
                        $telepulesek['fel'] = 0;
                        $telepulesek['le'] = 0;
                        //$a += 1;
                        $first = false;
                    }
                    
                    else
                    {
                        $telepulesek = $params['telepulesek'][$a];
                    }
                    //var_dump($a, $first);

                    $tav += $telepulesek['tav'];
                    $ossztav += $telepulesek['tav'];
                    $szakaszfel += $telepulesek['fel'];
                    $szakaszle += $telepulesek['le'];
                    $a++;
            ?>
                <tr>
                    <td style="display:none;"><?= $telepulesek['id']?></td>    
                    <td><?= $telepulesek['telepules']?></td>
                    <td><?= $telepulesek['hely']?></td>
                    <td><?= $telepulesek['locn']?></td>
                    <td><?= $telepulesek['loce']?></td> 
                    <td><?= $telepulesek['utszam']?></td>   
                    <td><?= $telepulesek['tav']?></td>
                    <td><?= $telepulesek['fel']?></td>
                    <td><?= $telepulesek['le']?></td>
                </tr>
            <?php endwhile;?>      
            </tbody>
        </table>
    </div>
<h3>Szakasz táv: <?= $tav ?> km</h3>
<h3>Szakasz fel: <?= $szakaszfel ?> méter</h3>
<h3>Szakasz le: <?= $szakaszle ?> méter</h3>
<h3>Össztáv: <?= $ossztav ?> km</h3>
<hr>
<hr>
<?php $szakaszSzama++; ?>

                
<?php endwhile ?>
<!-- A MEGADOTT KM-ENKÉNTI SZAKASZOKBA BELE NEM FÉRŐ TELEPÜLÉSEK -->
<!-- <h3> 'a' értéke:  <?= $a ?> </h3> -->
<?php 
    if ($a < count($params['telepulesek'])) : ?>
    <h5><?= $szakaszSzama ?>. szakasz</h5>
    <table class="table table-striped">
    <thead >
        <tr>
            <th style="display:none;">id</th>
            <th>település</th>
            <th>hely</th>
            <th>locn</th>
            <th>loce</th>
            <th>útszám</th>
            <th>táv</th>
            <th>fel</th>
            <th>le</th>
        </tr>
    </thead>
    <tbody>
        <?php 
            $tav = 0;
            $szakaszfel = 0;
            $szakaszle = 0;
            $first = true;
            $a -= 1;
            //var_dump($params['telepulesek']);
            for ($a; $a < count($params['telepulesek']); $a++) : 
                
                if ($first == true) // ha ez az adott táblázat első sora, kinullázza az értékeket
                {
                    $telepulesek = $params['telepulesek'][$a];
                    $telepulesek['tav'] = 0;
                    $telepulesek['utszam'] = '----';
                    $telepulesek['fel'] = 0;
                    $telepulesek['le'] = 0;
                    //$a += 1;
                    $first = false;
                }
                
                else
                {
                    $telepulesek = $params['telepulesek'][$a];
                }
            
                $tav += $telepulesek['tav'];
                $ossztav += $telepulesek['tav'];
                $szakaszfel += $telepulesek['fel'];
                $szakaszle += $telepulesek['le'];
            ?>
            <tr>
                <td style="display:none;"><?= $telepulesek['id']?></td>    
                <td><?= $telepulesek['telepules']?></td>
                <td><?= $telepulesek['hely']?></td>
                <td><?= $telepulesek['locn']?></td>
                <td><?= $telepulesek['loce']?></td> 
                <td><?= $telepulesek['utszam']?></td>   
                <td><?= $telepulesek['tav']?></td>
                <td><?= $telepulesek['fel']?></td>
                <td><?= $telepulesek['le']?></td>
            </tr>
        <?php endfor; ?>
    </tbody>
</table>

<h3>Szakasz táv: <?= $tav ?> km</h3>
<h3>Szakasz fel: <?= $szakaszfel ?> méter</h3>
<h3>Szakasz le: <?= $szakaszle ?> méter </h3>
<h3>Össztáv: <?= $ossztav ?> km</h3>
<?php endif; ?>
<hr>
<hr>