<?php if($params['isAuthorized']): //csak akkor jelenik meg a gomb, ha be van jelentkezve ?>
    <h4 style="float: right">Bejelentkezve, mint: <?=$params['userName']?></h4>
<?php endif; ?>
<br>
<br>
<div > <!-- class="container"  -->
    <div class="container-fluid">
        <form action="/Bringatura_MKK/utvonal-saved" method="GET">
            <div class="forcenter">
                <select class="form-select" name="userid" hidden>
                    <option selected value=<?= $params['userId']?>><?= $params['userId']?></option>
                </select>
                <button type="submit" class="btn btn-warning">Mutasd a mentett utat</button>
            </div>
        </form>
        <br />
        <form action="/Bringatura_MKK/utvonal" method="GET">  <!--class="row g-3" -->
            <div class="forcenter">
                <label class="form-label">Indulás: </label>
            </div>
            <div class="forcenter">
                <select class="form-select form-select-lg mb-3" name="start">
                    <?php foreach ($params['telepulesek'] as $telepules) : ?>
                        <option value=<?= $telepules['id']?>><?= $telepules['telepules']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="forcenter"> <!--class="col-auto"-->
                <label class="form-label">Érintsd: </label>
            </div>
            <div class="forcenter">
                <select class="form-select form-select-lg mb-3" name="touching">
                    <?php foreach ($params['telepulesek'] as $telepules) : ?>
                        <option value=<?= $telepules['id']?>><?= $telepules['telepules']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="forcenter">
                <label class="form-label">Érkezés: </label>
            </div>
            <div class="forcenter">
                <select class="form-select form-select-lg mb-3" name="end">
                    <?php foreach ($params['telepulesek'] as $telepules) : ?>
                        <option value=<?= $telepules['id']?>><?= $telepules['telepules']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="forcenter">
                <button type="submit" class="btn btn-success">Mutasd az útvonalat</button>
            </div>
        </form>
        <hr>
    </div>
</div>
