<div style="text-align:center">
    <hr>
    <form action="/Bringatura_MKK/varosok-megtekintese" method="GET">
        <button type="submit" class="btn btn-sm btn-primary m-2">Teljes útvonal</button>
    </form>
    <hr>
    <br>
    <br>
    <hr>
    <form action="/Bringatura_MKK/utvonal-valaszto" method="GET">
        <button type="submit" class="btn btn-sm btn-success m-2">Útvonal tervező</button>
    </form>
    <hr>
</div>