<div class="card p-3 m-2">
    <div class="jumbotron text-center">
        <h2>A tartalom megtekintéséhez bejelentkezés szükséges</h2>
    </div>
</div>

<?php if ($params['info'] === "registrationSuccessful") : ?>
    <div class="alert alert-success">
        Regisztráció sikeres!
    </div>
<?php endif ?>

<?php if ($params['info'] === "invalidCredentials") : ?>
    <div class="alert alert-danger">
        Helytelen bejelentkezési adatok! Kérem adja meg a helyes adatokat!
    </div>
<?php endif ?>

<?php if ($params['info'] === "existingEmail") : ?>
    <div class="alert alert-danger">
        A megadott email címmel már van regisztráció! Kérem adjon új adatokat!
    </div>
<?php endif ?>

<?php if ($params['info'] === "noData") : ?>
    <div class="alert alert-danger">
        Regisztrációhoz minden mező kitöltése kötelező! Kérem adja meg újra az adatokat!
    </div>
<?php endif ?>

<?php if ($params['info'] === "pwError") : ?>
    <div class="alert alert-danger">
        A megadott jelszavak nem azonosak! Kérem adja meg újra az adatokat!
    </div>
<?php endif ?>


<?php if ($params['isRegistration'] || $params['info'] === "existingEmail" || $params['info'] === "noData" || $params['info'] === "pwError") : ?>
    <form action="/Bringatura_MKK/register" method="POST"> 
    <label class="w-100">
        Felhasználónév:
        <input class="form-control" type="text" name="name">
    </label>

    <label class="w-100">
        Email cím:
        <input class="form-control" type="email" name="email">
    </label>

    <label class="w-100">
        Jelszó:
        <input class="form-control" type="password" name="password_1">
    </label>
    <label class="w-100">
        Jelszó mégegyszer:
        <input class="form-control" type="password" name="password_2">
    </label>
    <button type="submit" class="btn btn-success form-control">Regisztráció</button>
    Van már felhasználói fiókod?
    <a href="<?= $params['url'] ?>?">Bejelentkezés</a>
    </form>

<?php else : ?>
    <form action="/Bringatura_MKK/login" method="POST">
    <label class="w-100">
        Email cím:
        <input class="form-control" type="email" name="email">
    </label>

    <label class="w-100">
        Jelszó:
        <input class="form-control" type="password" name="password">
    </label>
    <button type="submit" class="btn btn-primary form-control">Bejelentkezés</button>
    Nincs még felhasználói fiókod?
    <a href="<?= $params['url'] ?>?&isRegistration=1">Regisztráció</a>
</form>
<?php endif ?>




