<!DOCTYPE html>
<html lang="hu">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
        
        <!--
        
        reklámok elhelyezhetőségére 3 gridre kell osztani
        <div class="w3-col l2 m12" id="right">
        <div class='w3-col l10 m12' id='main'>  

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-3 col-md-6 col-lg-4 bg-success">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </div>
            <div class="col-sm-9 col-md-6 col-lg-8 bg-warning">
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
            </div>
            </div>
        </div>   -->
        <link rel="stylesheet" href="././public/style.css">
        <title>Bringatúra_MKK</title>
    </head>

    <body>
        <div class="bg-warning">    
            <a class="navbar-brand" href="/Bringatura_MKK/">Magyarország Körbe Kerekezve</a>
        </div>

        <nav class="navbar navbar-expand-md bg-light navbar-light sticky-top">
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/Bringatura_MKK/">Kezdőoldal</a>
                    </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <li class="nav-item">
                        <a class="nav-link" href="bemutatkozas.php">Bemutatkozás</a>
                    </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="/Bringatura_MKK/tervezo">Tervező</a>
                    </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" id="navbardrop" data-bs-toggle="dropdown">Tervező</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="/Bringatura_MKK/varosok-megtekintese">Teljes útvonal</a>
                            <a class="dropdown-item" href="/Bringatura_MKK/utvonal-valaszto">Útvonal tervező</a>
                            <a class="dropdown-item" href="/Bringatura_MKK/utvonal-valaszto-km">Útvonal tervező km</a>
                            <!--<a class="dropdown-item" href="#">Link 3</a>-->
                        </div>
                    </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <li class="nav-item">
                        <a class="nav-link" href="/Bringatura_MKK/contact">Kapcsolat</a>
                    </li>
                </ul>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <?php if($params['isAuthorized']): //csak akkor jelenik meg a gomb, ha be van jelentkezve ?>
                    <form action="/Bringatura_MKK/logout" method="POST">
                        <button type="submit" class="btn btn-sm btn-danger m-2">Kijelentkezés</button>
                    </form>
                <?php endif; ?>
            </div>  
        </nav>
        <div class="container">
            <?= $params['content'] ?>
            <br>
            <footer>
                <p>
                    <span>Túrázz Kétkeréken Egyesület &#9734;&#9734;&#9734; Majercsik Zsolt Web-Dev</span>
                    <span>2023-2025</span>
                </p>
            </footer>
        </div>
        <button onclick="topFunction()" id="myBtn" title="Lapteteje">&#8896;</button>
    </body>
    <script src="././public/goToTop.js"></script>
</html>